<?php

namespace app\admin\controller\cross;

/*use app\admin\model\User;*/
use app\common\controller\Backend;

use think\Db;
use think\Request;
use wslibs\wsform\WsForm;
use wslibs\wszc\Dvalue;
use wslibs\wsform\InputType;
use wslibs\wsform\Item;
use wslibs\wszc\LoginUser;
use wslibs\wszc\Constant;
use wslibs\wszc\Dcp;
use wslibs\wszc\Ddocs;

use wslibs\wszc\DocContract;
use wslibs\wszc\Ds;

use wslibs\wszc\Dossier;
use wslibs\wszc\DossierLog;
use wslibs\wszc\User;


class Addfile extends Backend
{

    protected $model = null;

    public function _initialize()
    {

        $this->noNeedLogin = ['add'];

        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function add()
    {



        $datas = json_decode(file_get_contents("php://input"),true);

        if(input("dayin")==33){
            dump($datas);

            exit;
        }

        if(!$datas){
            echo 0;
            exit;
        }


        $dossier_id = (int)$datas['dossier_id'];


        foreach ($datas['path'] as $k=>$v){
            Dvalue::addFileToDocByDocMode($dossier_id, $v['mod_id'],Dvalue::mkFileValue($v['val'],$v['describe']),User::getLoginUid()-0>0?User::getLoginUid():13);
        }


        echo 1;
        exit;

    }



    public function index()
    {
        if($this->request->isPost()){
            $data = $this->request->param();

            $addData = [
                'province'=>$data['province'],
                'city'=>$data['city'],
                'district'=>$data['area'],
                'address'=>$data['address'],
                'speciality'=>$data['speciality'],
                'avatar'=>ltrim($data['row']['img'],'/'),
            ];

            Db::name('zcy')->where('idid',LoginUser::getIdid())->update($addData);

            $this->success("success",url('dossier.dlist/index'),['ref'=>'addtabs']);
            exit;
        }

        if($this->request->isAjax())
        {

            /**
             * 读取省市区数�?,联动列表
             */

            $province = $this->request->get('province');
            $city = $this->request->get('city');
            $where = ['pid' => 0, 'level' => 1];
            $provincelist = null;
            if ($province !== '') {
                if ($province) {
                    $where['pid'] = $province;
                    $where['level'] = 2;
                }
                if ($city !== '') {
                    if ($city) {
                        $where['pid'] = $city;
                        $where['level'] = 3;
                    }
                    $provincelist = Db::name('area')->where($where)->field('id as value,name')->select();
                }
            }
            $this->success('', null, $provincelist);

        }

        $info = Db::name('zcy')
            ->alias('zcy')
            ->join('idcards id','id.id = zcy.idid')
            ->field('zcy.*,id.sign_img')
            ->where('zcy.idid',LoginUser::getIdid())
            ->find();
        $info['province_name'] = $this->getName($info['province']);
        $info['city_name'] = $this->getName($info['city']);
        $info['district_name'] = $this->getName($info['district']);


        if($info['avatar']){
            $row['img'] = $info['avatar'];
            $row['show'] = IMG_SITE_ROOT.$info['avatar'];

            $this->assign('row',$row);
        }
        if($info['sign_img']){
            $info['sign_img'] = IMG_SITE_ROOT.$info['sign_img'];
        }

        $this->assign($info);
        return $this->fetch();
    }

    private function getName($id)
    {
        return Db::name('area')->where('id',$id)->find()['name'];
    }

    /**
     * 读取省市区数�?,联动列表
     */
    public function area()
    {
        $province = $this->request->get('province');
        $city = $this->request->get('city');
        $where = ['pid' => 0, 'level' => 1];
        $provincelist = null;
        if ($province !== '') {
            if ($province) {
                $where['pid'] = $province;
                $where['level'] = 2;
            }
            if ($city !== '') {
                if ($city) {
                    $where['pid'] = $city;
                    $where['level'] = 3;
                }
                $provincelist = Db::name('area')->where($where)->field('id as value,name')->select();
            }
        }
        $this->success('', null, $provincelist);
    }

    public function initInfo()
    {

        $form = new WsForm();
        $form->setFormTitleTip("请填写资");


        $item = new Item();
        $item->varName("name")->varTitle("姓名")->inputType(InputType::text);
        $form->addItem($item);

        $item = new Item();
        $item->varName("phone")->varTitle("手机�?")->inputType(InputType::text);
        $form->addItem($item);

        $item = new Item();
        $item->varName("diqu")->varTitle("住址")->inputType(InputType::citypicker);
        $form->addItem($item);

        $item = new Item();
        $item->varName("address")->varTitle("详细地址")->inputType(InputType::text);
        $form->addItem($item);

        $item = new Item();
        $item->varName("speciality")->varTitle("专业特长")->inputType(InputType::textarea);
        $form->addItem($item);

        $item = new Item();
        $item->varName("img")->varTitle("头像")->isUploadFile(true);
        $form->addItem($item->required(true));


        $form->setMakeType(WsForm::Type_Form);
        $form->makeForm("cross/addfile/setinfo");
    }


    public function editstr()
    {
        $data = $this->request->param();

        if(!$data['dossier_id']){
            echo -1;
            exit;
        }

 
        if($data['p']-1==0){
            Db::name('dossier')->where('id',$data['dossier_id'])->update(['request'=>$data['qingqiu']]);
        }else{

            Db::name('dossier')->where('id',$data['dossier_id'])->update(['reasons'=>$data['qingqiu']]);
        }


        echo 100;
        exit;

    }


    public function court()
    {

        
        $d_id = $this->request->param("id/d");
        $again = (int)$this->request->param("again/d");
        $is_phone = (int)$this->request->param("is_phone/d");


        if ($again) {
            $gid = Constant::FILE_GROUP_cxzhidingzhongcaiyuan;
        } else {
            $gid = Constant::FILE_GROUP_zhidingzhongcaiyuan;
        }

        $find = Db::name("court")->where("dossier_id = '$d_id' and  status<>0")->order("id desc")->find();


        if (!$again) {

            if ($find['status'] == 1) {
                $this->success("已经组庭了，但尚未完善组庭资", url('dossier.cp/doclist', array("id" => $d_id, "gid" => $gid, "exid" => $find['id'])));
            }
        }


        if ($this->request->isPost()  || $is_phone==1) {
            $postdata = $this->request->post("row/a");

            if ($find) {
                if ($again == 1) {
                    //$gid = Constant::FILE_GROUP_zuting_again;
                    Db::name("arbitrator")->where("dossier_id = '$d_id' and court_id={$find['id']} ")->update(["status" => 0]);
                    Db::name("court")->where("id = '{$find['id']}'")->update(['status' => 0]);
                    Db::name("huibi")->where("court_id = '{$find['id']}'")->update(['is_valid' => 0]);
                    DossierLog::addLog($d_id, $this->getCurentUserId(), LoginUser::getUserName(), DossierLog::LOG_TYPE_SET_UP_COURT);
                }
            }


            $zcy_id = $postdata['name'];


            $re = Dcp::zuting($d_id, $zcy_id, $again);


            if ($re['code'] == 1) {

                $doc_model = Constant::DOC_model_zutingtzs;
                $file_group = Constant::FILE_GROUP_zuting;
                $zcy_model = Constant::DOC_model_zhidingzhongcaiyuan;
                if ($again) {
                    $doc_model = Constant::DOC_model_againzuting;
                    $file_group = Constant::FILE_GROUP_zuting_again;
                    $zcy_model = Constant::DOC_model_cxzhidingzhongcaiyuan;

                    Dvalue::saveUniqueValueByDocMode($d_id, Constant::DOC_model_cxzhidingzhongcaiyuan, "AgainReason", $postdata['reason'], $re['id']);

                }


                Ds::sendGroupFileToDocRole($d_id, $gid, Constant::D_Role_ZhongCaiWei_JiGou, [], $re['id']);


                Db::name("court")->where("id = " . $re['id'])->update(['status' => 2]);



                Dossier::changeStatus($d_id, [3, 35]);


                DocContract::initContract(Ddocs::getOrInitFile($d_id,$zcy_model, $re['id'])['id']);

                $is_phone==1  ? $this->success("提交成功") :

                $this->success("提交成功", "", ['alert' => 1, 'wsreload' => 1]);

//
//                $rurl = DocContract::gotoAutoSignUrl(Ddocs::getOrInitFile($d_id,$zcy_model, $re['id'])['id'].','.Ddocs::getOrInitFile($d_id,$doc_model, $re['id'])['id'], Constant::mkDmpUrl($d_id, $file_group, $re['id']));
//               $this->redirect($rurl);
              //  $this->success("", $rurl, ['alert' => 0, "wsreload" => 2]);


                // $this->redirect(url('dossier.cp/doclist', array("id" => $d_id, "gid" => $gid, "exid" => $re['id'])));

            } else {
                $this->error($re['msg']);
            }
        } else {

            $dossierInfo = Dossier::getSimpleDossier($d_id);
            $hasChoose = Db::name('arbitrator')->field('zcy_uid')->where("dossier_id",$d_id)->selectOfIndex('zcy_uid');
            $zcyList = Db::name("jigou_zcy")
                ->field("zc.name,zc.id,zc.province,zc.city,zc.district,zc.total,zc.failed_num,zc.finish_num,a.name as province_name,aa.name as city_name,aaa.name as district_name,zc.avatar")
                ->alias("jz")
                ->join("zcy zc", "jz.zcy_id = zc.id",'left')
                ->join("zc_area a", "zc.province = a.id",'left')
                ->join("zc_area aa", "zc.city = aa.id",'left')
                ->join("zc_area aaa", "zc.district = aaa.id",'left')
                ->where('jz.jg_id',$dossierInfo['zc_jg_id'])
                ->whereNotIn('zc.id',$hasChoose)
                ->order('zc.finish_num desc,zc.total desc')
                ->paginate(20,false,['query' => Request::instance()->param()]);

//            for($i=4;$i<40;$i++){
//                $zcyList[$i] = $zcyList[0];
//            }
//
//
            $page = $zcyList->render();


            $thirdInfo = Db::name('third_client')->where('id',$dossierInfo['third_jg_id'])->find();

            $arr1 = [];
            $arr2 = [];
            $arr3 = [];

            if(input('lee')==909){
                dump($dossierInfo);
                dump($thirdInfo);
            }
            foreach ($zcyList as $k=>$v){

                if($v['province']-$thirdInfo['province'] !=  0){
                    $arr1[$k] = $v;
                    $arr1[$k]['remind'] = '推荐';//'#007520';
                    $arr1[$k]['remind_show'] = 1;
                }elseif($v['province'] - $thirdInfo['province'] == 0 && $v['city'] - $thirdInfo['city'] != 0){
                    $arr2[$k] = $v;
                    $arr2[$k]['remind'] = '推荐';//'#fcbaba';
                    $arr2[$k]['remind_show'] = 1;
                }else{
                    $arr3[$k] = $v;
                    $arr3[$k]['remind'] = '�?';

                }


            }


            $zcyList_1 = array_merge(array_values($arr1),array_values($arr2),array_values($arr3));

            foreach ($zcyList_1 as $k=>$v){
                if($v['avatar']){
                    $zcyList_1[$k]['show'] = IMG_SITE_ROOT.$v['avatar'];
                }


                if(!$v['id']){
                    unset($zcyList_1[$k]);
                }

            }

            if(input('leed')==1){
                dump($zcyList_1);
            }

            /*$this->assign("d_id",$d_id);*/


            $this->assign("page", $page);
            $this->assign("is_again", $again);
            $this->assign("zcyList", $zcyList_1);
            $this->use_form_Js();
            return $this->fetch();
        }
        /*dump($zcyList);*/
    }

    public function getCurentUserId()
    {
        return User::getLoginUid();
    }


    
}