<?php
/**
 * Created by PhpStorm.
 * User: Lee
 * Date: 2018/4/26
 * Time: 18:50
 */
namespace app\admin\controller;

use app\common\controller\Backend;
use EasyWeChat\Message\Image;
use wslibs\wsform\Item;
use wslibs\wsform\WsForm;
use wslibs\wsform\InputType;
use think\Db;
use app\admin\model\DocManager;

class Docshow extends Backend
{
    public function _initialize()
    {
//        $this->use_action_js();
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function initadd()
    {
        $form = new WsForm();

        $form->addItem((new Item())->varName('name')->varTitle('姓名')->inputType(InputType::text));

        $form->setMakeType(WsForm::Type_Form);
        $form->makeForm("Docshow/docshow");

    }

    public function docshow()
    {

        $doc_id = $this->request->param('ids/d');
        if(!((int)$doc_id)){
            $this->error("缺少参数");
        }

        $docInfo = DocManager::getAttrInfo($doc_id);
        if(!$docInfo){
            $this->error("信息错误");
        }

        $info = Db::query("select * from zc_dma where doc_model_id = ".$docInfo['doc_model_id']." and type = 1 and sub_type <> 0 ");


        $drav = Db::name('drav')->where("doc_id = ".$doc_id)->select();

        $out = [];

        foreach ($info as $k=>$v){
            foreach ($drav as $key=>$val){
                if($v['id']==$val['attr_id']){
                    $out[$v['flag']] = $val['value'];
                }
            }
        }

        if($this->request->isPost()){

            $param = $this->request->post("row/a");

            foreach($param as $k=>$v){
                if(empty($v)){
                    $this->error("请填写完整数据");
                }
            }


            if(!$drav){

                Db::startTrans();
                $data = [];
                foreach($info as $k=>$v){


                    $data[$k]['doc_id'] = $doc_id;
                    $data[$k]['attr_id'] = $v['id'];
                    $data[$k]['value'] = $param[$v['flag']];
                    $data[$k]['status'] = 1;


                }

                $re = Db::name('drav')->insertAll($data);
                $res = DocManager::setAttrSuccess($doc_id);
                if($re && $res){
                    Db::commit();


                    $this->success("成功");
                }else{
                    Db::rollback();
                    $this->error("失败");
                }
            }else{
                foreach($drav as $k=>$v){

                    $data = [];
                    $data['value'] = $param[$v['flag']];
                    Db::name('drav')->where("id = ".$v['id'])->update($data);

                }

            }

        }

        $form = new WsForm();

        foreach($info as $k=>$v){
            if($v['type']==1){
                switch ($v['sub_type']){
                    case 1: $mid = InputType::text;
                        $form->addItem((new Item())->varName($v['flag'])->varTitle($v['name'])->inputType($mid));

                    break;
                    case 2: $mid = InputType::radio;
                            $arr = explode(';',$v['op']);
                            $middle = [];
                            foreach ($arr as $key=>$val){
                                $middle[$val] = $val;
                            }
                        $form->addItem((new Item())->varName($v['flag'])->varTitle($v['name'])->itemArr($middle)->inputType($mid));
                    break;
                    case 3: $mid = InputType::checkbox;break;
                    case 4: $mid = InputType::select;break;
                    case 5: $mid = InputType::textarea;break;
                }
            }

        }

        $form->setMakeType(WsForm::Type_Form);

        $this->assign('row',$out);
        return $form->display($this);
    }

    public function docshowtest()
    {

        $doc_id = $this->request->param('ids/d');
        if(!((int)$doc_id)){
            $this->error("缺少参数");
        }

        $docInfo = DocManager::getAttrInfo($doc_id);
        if(!$docInfo){
            $this->error("信息错误");
        }

        $info = Db::query("select * from zc_dma where type = 1  and  doc_model_id = ".$docInfo['doc_model_id'] );


        $drav = Db::name('drav')->where("doc_id = $doc_id")->select();

        $out = [];

        foreach ($info as $k=>$v){
            foreach ($drav as $key=>$val){
                if($v['id']==$val['attr_id']){
                    $out[$v['flag']] = $val['value'];
                }
            }
        }

        $l_out = [];
        $infoCopy = $info;
        foreach ($info as $k=>$v){
            foreach ($infoCopy as $key=>$val){

                if($v['id'] == $val['gid']){
                    $l_out[$k]['val'][] = $val;
                    $l_out[$k]['name'] = $v['name'];
                    $l_out[$k]['flag'] = $v['flag'];
                    unset($infoCopy[$key]);
                }

            }

        }


        foreach ($infoCopy as $k=>$v){
            dump($v);
        }
 

        if($this->request->isPost()){

            $param = $this->request->post("row/a");

            foreach($param as $k=>$v){
                if(empty($v)){
                    $this->error("请填写完整数据");
                }
            }


            if(!$drav){

                Db::startTrans();
                $data = [];
                foreach($info as $k=>$v){


                    $data[$k]['doc_id'] = $doc_id;
                    $data[$k]['attr_id'] = $v['id'];
                    $data[$k]['value'] = $param[$v['flag']];
                    $data[$k]['status'] = 1;


                }

                $re = Db::name('drav')->insertAll($data);
                $res = DocManager::setAttrSuccess($doc_id);
                if($re && $res){
                    Db::commit();


                    $this->success("成功");
                }else{
                    Db::rollback();
                    $this->error("失败");
                }
            }else{
                foreach($drav as $k=>$v){

                    $data = [];
                    $data['value'] = $param[$v['flag']];
                    Db::name('drav')->where("id = ".$v['id'])->update($data);

                }

            }

        }

        $form = new WsForm();

        foreach($info as $k=>$v){
            if($v['type']==1){
                switch ($v['sub_type']){
                    case 1: $mid = InputType::text;
                        $form->addItem((new Item())->varName($v['flag'])->varTitle($v['name'])->inputType($mid));

                    break;
//                    case 2: $mid = InputType::radio;
//                            $arr = explode(';',$v['op']);
//                            $middle = [];
//                            foreach ($arr as $key=>$val){
//                                $middle[$val] = $val;
//                            }
//                        $form->addItem((new Item())->varName($v['flag'])->varTitle($v['name'])->itemArr($middle)->inputType($mid));
//                    break;
                    case 3: $mid = InputType::checkbox;break;
                    case 4: $mid = InputType::select;break;
                    case 5: $mid = InputType::textarea;break;
                }
            }

        }

        $form->setMakeType(WsForm::Type_Form);

        $this->assign('row',$out);

        $tmp = $this->display($form->makeForm());


        $this->assign("ids",$doc_id);
        $this->assign("content",$tmp);

        return $this->fetch('docshow');
    }


    public function doclist()
    {
        $dossier_id = $this->request->param("dossier_id/d");
        if(!$dossier_id){
            $this->error("缺少参数");
        }

        $list = Db::name('dr')->where('dossier_id',$dossier_id)->select();
        dump($list);


        $this->assign('list',$list);
        return $this->fetch();

    }
 

}