<?php
/**
 * Created by PhpStorm.
 * User: apple
 * Date: 2018/4/27
 * Time: 上午10:40
 */

namespace app\admin\controller;


use app\common\controller\Backend;
use think\Db;
use think\Request;
use wslibs\wsform\InputType;
use wslibs\wsform\Item;
use wslibs\wsform\WsForm;
use wslibs\wszc;
use wslibs\wszc\DossierUser;
use wslibs\wszc\LoginUser;


class Dossierlist extends Backend
{
    private $login_user_idid;

    private $arr = [0=>'未知',1=>'银行仲裁',2=>'其他类型'];
    private $arr_valid = [1=>'有效',0=>'取消驳回'];
    private $arr_du_type = [1=>'自然人',2=>'机构',3=>'机构法人'];
    private $arr_status = [1=>'申请中',2=>'已受理',3=>'答辩质证',4=>'组庭中',10=>'已完成',0=>'取消驳回'];

    public function _initialize()
    {
        $this->login_user_idid = LoginUser::getIdid();
        $this->use_action_js();
        $this->noNeedRight = ['*'];
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function initview()
    {
        $form = New WsForm();

        $form->setMultiUrl("Dosserlist/index");
        $form->setAddUrl("Dosserlist/add");
        $form->setDelUrl("Dosserlist/delete");
        $form->setEditUrl("Dosserlist/add");
        $form->setListUrl("Dosserlist/index");

        $form->addItem((new Item())->varName("id")->varTitle("ID")->inputType(InputType::text));
        $form->addItem((new Item())->varName("title")->varTitle("标题")->inputType(InputType::text));

        $form->addItem((new Item())->varName("jg_name")->varTitle("仲裁机构名称")->inputType(InputType::text));
        $form->addItem((new Item())->varName("address")->varTitle("机构地址")->inputType(InputType::text));
        $form->addItem((new Item())->varName("no")->varTitle("卷宗编号")->inputType(InputType::text));
        $form->addItem((new Item())->varName("zno")->varTitle("仲裁受理编号")->inputType(InputType::text));
        $form->addItem((new Item())->varName("type")->varTitle("业务类型")->inputType(InputType::text)->defaultValue("1"));
//        $form->addItem((new Item())->varName("zc_jg_id")->varTitle("仲裁机构")->inputType(InputType::text));
        $form->addItem((new Item())->varName("third_jg_id")->varTitle("第三方机构")->inputType(InputType::text));
        $form->addItem((new Item())->varName("status")->varTitle("状态")->inputType(InputType::text));
        $form->addItem((new Item())->varName("addtime")->varTitle("添加时间")->inputType(InputType::text));
        $form->addItem((new Item())->varName("is_valid")->varTitle("是否失效")->inputType(InputType::text));
//        $form->addItem((new Item())->varName("third_order_id")->varTitle("第三方标识")->inputType(InputType::text));
        $form->addItem((new Item())->varName("money")->varTitle("仲裁金额")->inputType(InputType::text));
        $form->addItem((new Item())->varName("dispute_money")->varTitle("争议金额")->inputType(InputType::text));
        $form->addItem((new Item())->varName("du_type")->varTitle("自然人/机构/法人")->inputType(InputType::text));
        $form->addItem((new Item())->varName("du_name")->varTitle("用户名称")->inputType(InputType::text));
        $form->addItem((new Item())->varName("role")->varTitle("角色")->inputType(InputType::text));
        $form->addItem((new Item())->varName("id_num")->varTitle("身份证号/信用代码")->inputType(InputType::text));
        $form->addItem((new Item())->varName("phone")->varTitle("联系方式")->inputType(InputType::text));

        $form->setMakeType(WsForm::Type_Table);
        $form->makeForm("Dosserlist/index");
    }

    public function addview()
    {

        $form = New WsForm();
        $form->setMultiUrl("Dosserlist/index");
        $form->setAddUrl("Dosserlist/add");
        $form->setDelUrl("Dosserlist/delete");
        $form->setEditUrl("Dosserlist/add");
        $form->setListUrl("Dosserlist/index");

        $form->addItem((new Item())->varName("title")->varTitle("标题")->inputType(InputType::text)->required(true));
        $form->addItem((new Item())->varName("no")->varTitle("卷宗编号")->inputType(InputType::text)->required(true));
        $form->addItem((new Item())->varName("zno")->varTitle("仲裁受理编号")->inputType(InputType::text)->required(true));
        $form->addItem((new Item())->varName("type")->varTitle("业务类型")->inputType(InputType::select)->itemArr([1=>'银行仲裁'])->defaultValue("银行仲裁"));
        $zc_jg = Db::name('jigou')->where("status=1")->select();
        $zc_jg = array_column($zc_jg,'name','id');
        $form->addItem((new Item())->varName("zc_jg_id")->varTitle("仲裁机构")->inputType(InputType::select)->itemArr($zc_jg));
        $form->addItem((new Item())->varName("third_jg_id")->varTitle("第三方机构")->inputType(InputType::text));
        $form->addItem((new Item())->varName("status")->varTitle("状态")->inputType(InputType::radio)->itemArr([1=>'启用',0=>'不启用']));
        $form->addItem((new Item())->varName("addtime")->varTitle("添加时间")->inputType(InputType::datetime)->defaultValue(time()));
        $form->addItem((new Item())->varName("is_valid")->varTitle("是否失效")->inputType(InputType::radio)->itemArr([1=>'有效',0=>'失效']));
        $form->addItem((new Item())->varName("third_order_id")->varTitle("第三方标识")->inputType(InputType::text));
        $form->addItem((new Item())->varName("money")->varTitle("仲裁金额")->inputType(InputType::text)->required(true));
        $form->addItem((new Item())->varName("dispute_money")->varTitle("争议金额")->inputType(InputType::text)->required(true));

        $form->setMakeType(WsForm::Type_Form);
        $form->makeForm("Dosserlist/add");
    }


    public function add(){
        $id = $id = $this->request->param('ids/i');
        $zc_jg = Db::name('jigou')->where("status=1")->select();
        $zc_jg_idlist = array_column($zc_jg,'name','id');
        $this->assign('zc_jg_idlist',$zc_jg_idlist);
        if(IS_AJAX){
            $data = Request::instance()->post('row/a');
            if($id){
                $res = Db::name('dossier')->where('id',$id)->update($data);
            }else{
                $data['addtime'] = time();
                $res = Db::name('dossier')->insert($data);
            }
            if($res){
                $this->success('成功');
            }else{
                $this->error('失败');
            }

        }else{
            if($id){
                $info = Db::name('dossier')->where("id='$id'")->find();
                $this->assign('row',$info);
            }
            return $this->fetch('add');
        }

    }


    public function delete(){
        $id = $id = $this->request->param('ids/i');
        if(!$id){
            $this->error('参数错误');
        }

        $re = Db::name("dossier")->where("id = '$id'")->delete();

        if($re){
            $this->success("删除成功");
        }else{
            $this->error("删除失败");
        }
    }


    public function dossierlist(){
        /*$map = [
            'du.role' => ['eq',1]
        ];*/
        ///*du.type as du_type,du.name as du_name,du.role,du.id_num,du.id_type,du.phone,*/
        $list = Db::name("dossier")->alias('d')
            /*->join('dossier_users du','du.dossier_id=d.id')*/
            ->join('jigou jg','d.zc_jg_id=jg.id')
            ->field('d.*,jg.name as jg_name,jg.address')
            /*->where($map)*/
                ->order('d.id desc')
            ->paginate(10);

        foreach ($list as $k => $v){
            $list[$k]['addtime'] = date('Y-m-d H:i:s',$v['addtime']);
            $list[$k]['type'] = $this->arr[$v['type']];
            $list[$k]['is_valid'] = $this->arr_valid[$v['is_valid']];
            $list[$k]['status'] = $this->arr_status[$v['status']];
            $list[$k]['is_valid'] = $this->arr_status[$v['is_valid']];
            $list[$k]['du_type'] = $this->arr_du_type[$v['du_type']];
        }

        if(input("sy")==1){
            $list = Db::name("dossier")->alias('d')
                /*->join('dossier_users du','du.dossier_id=d.id')*/
                ->join('jigou jg','d.zc_jg_id=jg.id')
                ->join('dossier_users du','du.dossier_id = d.id')
                ->field('d.*,jg.name as jg_name,jg.address')
                /*->where($map)*/
                ->select();

                dump($list);
            /*dump($this->login_user_idid);
            echo Db::name("dossier")->getLastSql();
            dump($list);
            dump($_SESSION);*/
        }

        $page = $list->render();
        $this->assign('page', $page);
        $this->assign("list",$list);
        return $this->fetch('dosserlist/list');
    }


    public function addDossier()
    {
        $idid = session("zc_admin_idid");
        $has = Db::name("dossier_users")->where("idid = '$idid'")->order("id desc")->find();
        $yw = Db::name("dossier")->where("status IN (1,2,3,4) and id = ".$has['dossier_id'])->find();
        if($yw){
            $url = url('dossier.info/index',['id' => $has['dossier_id']]);
            $this->error("你有未完成的业务，即将跳转至该业务",$url);
            /*echo Db::name("dossier")->getLastSql();
            dump($has);
            dump($yw);die;*/
        } else {
            Db::startTrans();
            $re1 = wszc\Dossier::add(session("admin.jg_id"),4,5);
            $re2 = wszc\Dossier::addLog($re1,session("zc_admin_uid"),"name");

            $dossierUser = new DossierUser();
            $re3 = $dossierUser->setPhone('13933863958')->setNameOrOrgname("宋扬")->setIdcardOrCreditno('130102199708280318')->setRole(1)->setType(1)->pushToDossier($re1)/*dossierID*/;

            if($re1 && $re2 && $re3){
                Db::commit();
                $this->success("成功");
            }else{
                Db::rollback();
                $this->error("失败");
            }
        }
    }
}