<?php
/**
 * Created by PhpStorm.
 * User: apple
 * Date: 2018/5/11
 * Time: 下午1:12
 */

namespace app\admin\controller;


use app\common\controller\Backend;

class Thirdjigou extends Backend
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function initView()
    {

    }
}