<?php
/**
 * Created by PhpStorm.
 * User: apple
 * Date: 2018/5/9
 * Time: 上午11:01
 */

namespace app\admin\controller;


use \app\common\controller\Backend;
use app\common\library\Email;

use dossier\DossierDoc;
use think\Config;
use think\Db;
use think\Session;
use wslibs\run\WsExce;
use wslibs\wszc\Constant;
use wslibs\wszc\datashow\DashboardLine;
use wslibs\wszc\DInfoValue;
use wslibs\wszc\dmail\Dmail;
use wslibs\wszc\Dmp;
use wslibs\wszc\Dossier;
use wslibs\wszc\dtime\Dtime;
use wslibs\wszc\LoginUser;
use wslibs\wszc\notice\Dnotice;
use wslibs\wszc\notice\Notice;
use wslibs\wszc\publicnumber\BaseVar;
use wslibs\wszc\publicnumber\kfmanager\Kfinfo;
use wslibs\wszc\publicnumber\MsgCrypt;
use wslibs\wszc\publicnumber\NewsModelWithDo;
use wslibs\wszc\publicnumber\wxencode\Prpcrypt;
use wslibs\wszc\publicnumber\wxencode\WXBizMsgCrypt;
use wslibs\wszc\publicnumber\NewsModel;
use wslibs\wszc\publicnumber\PublicNumber;
use wslibs\wszc\publicnumber\ReplyMsg;
use wslibs\wszc\publicnumber\Zhz;

class Zhztest extends Backend
{
    public function _initialize()
    {
        $this->noNeedLogin = ['*'];
        $this->use_action_js();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    public function tongzhishu()
    {

        $info = new DInfoValue(121);
        $test= $info::getTemplateData(1,1);
        dump($test);



        $this->assign('d',$test);
        $info = Db::name('dm')->where('id=13')->find();

        $view_content = $this->display($info['view_content']);
        dump($info['view_content']);
        $this->assign('view_content',$view_content);

        return $this->fetch();
    }

    public function bsqr()
    {

        $info = new DInfoValue(121);
        $test= $info::getTemplateData(1,1);
        dump($test);



        $this->assign('d',$test);
        $info = Db::name('dm')->where('id=32')->find();

        $view_content = $this->display($info['view_content']);
        dump($info['view_content']);
        $this->assign('view_content',$view_content);

        return $this->fetch();
    }
    public function index()
    {

        $info = new DInfoValue(121);
        $test= $info::getTemplateData(1,1);
        $test['info']['date'] = date('Y年m月d日',$test['info']['addtime']);
        dump($test);

        $this->assign('d',$test);
        $info = Db::name('dm')->where('id=1')->find();

        $view_content = $this->display($info['view_content']);
        $this->assign('view_content',$view_content);

        return $this->fetch();
    }
    public function guize()
    {
        $info = Db::name('dm')->where('id=14')->find();

        $this->assign('view_content',$info['view_content']);

        return $this->fetch();
    }

    public function mingce()
    {
        $info = Db::name('dm')->where('id=18')->find();

        $this->assign('view_content',$info['view_content']);

        return $this->fetch();
    }

    public function zuting()
    {
        $info = new DInfoValue(121);
        $test= $info::getTemplateData(1,1);
        dump($test);

        $this->assign('d',$test);
        $info = Db::name('dm')->where('id=20')->find();

        $view_content = $this->display($info['view_content']);
        dump($info['view_content']);
        $this->assign('view_content',$view_content);

        return $this->fetch();
    }
    public function pilou()
    {
        $info = new DInfoValue(121);
        $test= $info::getTemplateData(1,1);
        dump($test);

        $this->assign('d',$test);
        $info = Db::name('dm')->where('id=24')->find();

        $view_content = $this->display($info['view_content']);
//        dump($info['view_content']);
        $this->assign('view_content',$view_content);

        return $this->fetch();
    }
    public function huibi()
    {
        $info = new DInfoValue(121);
        $test= $info::getTemplateData(1,1);
        dump($test);

        $this->assign('d',$test);
        $info = Db::name('dm')->where('id=25')->find();

        $view_content = $this->display($info['view_content']);
        dump($info['view_content']);
        $this->assign('view_content',$view_content);

        return $this->fetch();
    }
    public function shengming()
    {
        $info = new DInfoValue(121);
        $test= $info::getTemplateData(1,1);
        dump($test);

        $this->assign('d',$test);
        $info = Db::name('dm')->where('id=23')->find();

        $view_content = $this->display($info['view_content']);
        dump($info['view_content']);
        $this->assign('view_content',$view_content);

        return $this->fetch();
    }
    public function caijue()
    {
        $info = new DInfoValue(121);
        $test= $info::getTemplateData(1,1);
        dump($test);

        $this->assign('d',$test);
        $info = Db::name('dm')->where('id=28')->find();

        $view_content = $this->display($info['view_content']);
        dump($info['view_content']);
        $this->assign('view_content',$view_content);

        return $this->fetch();
    }
    public function dabian()
    {
        $info = new DInfoValue(121);
        $test= $info::getTemplateData(1,1);
        dump($test);

        $this->assign('d',$test);
        $info = Db::name('dm')->where('id=5')->find();

        $view_content = $this->display($info['view_content']);
        dump($info['view_content']);
        $this->assign('view_content',$view_content);

        return $this->fetch();
    }

    public function test()
    {
//        $test= $this->create_zc_no('','');
//        echo Db::name('dossier')->getLastSql();
//        dump($test);
//        dump($this->getStatusColor(1));
//        dump($this->getStatusColor(2));
//        dump($this->getStatusColor(3));
//        dump($this->getStatusColor(4));
        dump($this->getStatusColor(5));
//        dump($this->getStatusColor(10));
//        dump($this->getStatusColor(0));
    }

    public function test_no()
    {
        $test= $this->create_zc_no(407,true);
        dump($test);
    }


    public function create_zc_no($dossier_id=0,$is_str=false)
    {

        $zno = $this->getMaxZcNo($dossier_id);

        if(!$zno) return false;

        if(!$dossier_id){
            $new_zno= str_pad(intval($zno['zno'])+1,5,'0',STR_PAD_LEFT);
            $time = time();
        }else{
            $new_zno = $zno['zno'];
            $time = $zno['addtime'];
        }

        if($is_str){
            $new_zno = $this->getZcNoByNo($new_zno,$time);
        }
        return $new_zno;
    }

    public function getMaxZcNo($dossier_id)
    {
        $map = [];
        $map['zno'] = array('neq','');
        if($dossier_id){
            $map['id'] = $dossier_id;
        }
        return Db::name('dossier')->where($map)->field('id,max(zno) as zno,addtime')->order('id desc')->find();
    }

    public function getZcNoByNo($zc_no,$time)
    {
        return '石裁上字['.date('Y',$time).']第'.$zc_no.'号';
    }



    public function create_zc_no1($dossier_id=0,$is_str=false)
    {
        $map = [];
        $map['zno'] = array('neq','');
        if($dossier_id){
            $map['id'] = $dossier_id;
        }

        $zno = Db::name('dossier')->where($map)->field('id,max(zno) as zno,addtime')->order('id desc')->find();

        if(!$zno) return false;

        if(!$dossier_id){

            $new_zno= str_pad(intval($zno['zno'])+1,5,'0',STR_PAD_LEFT);
            if($is_str){
                $new_zno = '石裁上字['.date('Y').']第'.$new_zno.'号';
            }
        }else{

            $new_zno = $zno['zno'];
            if($is_str){
                $new_zno = '石裁上字['.date('Y',$zno['addtime']).']第'.$zno['zno'].'号';
            }
        }

        return $new_zno;
    }
    public  function getStatusColor($status)
    {

        list($color_1,$color_2,$color_3,$color_4) = Constant::getColorClass();

        switch($status){
            case 0:
                $color = $color_1;
                break;
            case $status>0 && $status <3 :
                $color = $color_2;
                break;
            case $status>=3 && $status <=5:
                $color = $color_3;
                break;
            case 10:
                $color = $color_4;
                break;
            default :
                $color = $color_1;
                break;
        }

        return  $color;
    }

    public function test_test()
    {
        $did = $this->request->param('did/d');

        $info = new \wslibs\wszc\datashow\InfoShow();

        $list = $info->isNeedDaBian(true)->isNeedDanger(true)->isNeedDLog(true)->isNeedOperation(true)->isNeedZCY(true)->isNeedZhiZheng(true)->isNeedZuTing(true)->getData($did);

        dump($list);
    }

    public function test_count()
    {
        $jg_id = Db::name('jigou_zcy')->where("idid",LoginUser::getIdid())->find();
        $site_ = Db::name('jigou')->where("id",$jg_id['jg_id'])->find();
        $admin_ = Db::name('zcy')->where("id",$jg_id['zcy_id'])->find();
        dump(LoginUser::getIdid());
        dump($site_);
        dump($admin_);
    }

    public function zdzcytzs()
    {
        $info = new DInfoValue(121);
        $test= $info::getTemplateData(1,1);
        dump($test);

        $this->assign('d',$test);
        $info = Db::name('dm')->where('id=28')->find();

        $view_content = $this->display($info['view_content']);
        dump($info['view_content']);
        $this->assign('view_content',$view_content);

        return $this->fetch();
    }

    public function session_zcuser()
    {

        dump(Session::get());
        dump(Session::get('zcuser'));
        dump(Session::get('referer'));
        dump(Config::get('fastadmin'));

        dump(Config::get('upload'));
    }

    public function send_email()
    {
        $res = Email::instance()->to('15201634344@163.com','是多少')->from('935828672@qq.com','sds')->subject('这个是一个测试邮件')->message('这个是一个测试邮件这个是一个测试邮件这个是一个测试邮件这个是一个测试邮件这个是一个测试邮件这个是一个测试邮件这个是一个测试邮件这个是一个测试邮件这个是一个测试邮件')->send();
//        dump(Config::get('site'));

        dump(Email::instance()->getError());
        dump($res);

//        echo phpinfo();
    }

    public function send()
    {
        $smtpserver = "smtp.163.com";//SMTP服务器

        $smtpserverport =25;//SMTP服务器端口

        $smtpusermail = "15201634344@163.com";//SMTP服务器的用户邮箱

        $smtpemailto = '935828672@qq.com';//发送给谁

        $smtpuser = "15201634344";//SMTP服务器的用户帐号(或填写new2008oh@126.com，这项有些邮箱需要完整的)

        $smtppass = "935828672";//SMTP服务器的用户密码

        $mailtitle = '测试';//邮件主题

        $mailcontent = "<h1>".$_POST['content']."</h1>";//邮件内容

        $mailtype = "HTML";//邮件格式（HTML/TXT）,TXT为文本邮件

        //************************ 配置信息 ****************************

        $smtp = new SMTP($smtpserver,$smtpserverport,true,$smtpuser,$smtppass);//这里面的一个true是表示使用身份验证,否则不使用身份验证.

        $smtp->debug = false;//是否显示发送的调试信息

        $state = $smtp->sendmail($smtpemailto, $smtpusermail, $mailtitle, $mailcontent, $mailtype);



        echo "<div style='width:300px; margin:36px auto;'>";

        if($state==""){

            echo "对不起，邮件发送失败！请检查邮箱填写是否有误。";

            echo "<a href='index.html'>点此返回</a>";

            exit();

        }

        echo "恭喜！邮件发送成功！！";

        echo "<a href='index.html'>点此返回</a>";

        echo "</div>";
    }

    public function send_mail()
    {

        $headers = 'MIME-Version: 1.0' . "\r\n";
        $headers .= "Content-type: text/html; charset=".'utf8'. "\r\n";
        $headers .= "To: 浪荡小志 <935828672@qq.com>\r\n"; //收件人
        $headers .= "From: 小志 <15201634344@163.com>\r\n"; //发件人
        $result = mail('935828672@qq.com','测试', '这是一条测试消息', $headers);

        dump($result);
    }

    public function sendMail1()
    {
        $res = $this->sendMail('935828672@qq.com','市地税局','是多少');
        dump($res);
    }

    public function sendMail($address, $title, $message) {
        vendor('phpmailer.phpmailer.PHPMailerAutoload');
        $mail = new \PHPMailer();
        $mail->Host = "smtp.yeah.net"; //SMTP服务器
        $mail->Port = 25;  //邮件发送端口
        $mail->SMTPAuth = true;  //启用SMTP认证
        $mail->CharSet = "UTF-8"; //字符集
        $mail->Encoding = "base64"; //编码方式
        $mail->Username = "wenshizhengxin@yeah.net";  //你的邮箱
        $mail->Password = "wenshijituan1";  //你的密码
        $mail->Subject = "文始征信"; //邮件标题
        $mail->From = "wenshizhengxin@yeah.net";  //发件人地址（也就是你的邮箱）
        $mail->FromName = "文始征信";  //发件人姓名

        // 添加收件人地址，可以多次使用来添加多个收件人
        $mail->AddAddress($address);
        // 设置邮件正文
        $mail->Body = $message;
        //设置邮件主题
        $mail->Subject = $title;
        $mail->IsHTML(true);


        return $mail->send();
    }

    public function diaoqu_we()
    {
        $info = \think\Db::name("drv")->where("dossier_id",653)->select();

        dump($info);
    }

    public function ceshi()
    {
        $status = $this->request->param('type');


        return $this->fetch();
    }

    public function dmail()
    {
        $res = Dmail::instance()->addBeiShenqingren(743)->sendShouLiWenjianToBeiShenQingRen(743);

        dump($res);
    }

    public function dtime()
    {
        $list = Dtime::getTimeGroupForDid(35);

        dump($list);
    }

    public function localeconv()
    {
        dump( localeconv());
        dump( $res= nl_langinfo(MON_THOUSANDS_SEP));


    }
    public function weixin()
    {
//        $list_ = PublicNumber::get_menu_list();
//        $list_1 = \wslibs\wszc\publicnumber\Config::addAccessToken(\wslibs\wszc\publicnumber\Config::get_access_token(true));
//        $list = PublicNumber::getUserList();
//        $ip_list = PublicNumber::getWxIPList();

//        dump($list_);
//        dump($list);
//        dump($list_1);
//        exit;
//        dump($ip_list);
//        dump(\GuzzleHttp\json_decode('{"template_id_short":"TM00015"}',true));
//
//        $model = NewsModel::get_template_id_short();
//        $model_list = NewsModel::get_template_id_short();

//        dump($model);
//        dump($model_list);
//        $res = (new NewsModel(72))->zhongCaiTongZhi(2,'','http://zc.wszx.cc');
//        $res1 = (new NewsModel(72))->zhongCaizutingTongZhi(2,'','http://zc.wszx.cc');
//        $res2 = (new NewsModel(72))->zhongcaiCaiJueRenLingTongZhi(2,'','http://zc.wszx.cc','郑洪志');
//        dump($res);
//        dump($res1);
//        dump($res2);

//        $res = Dnotice::whenDmpFinish(82,4,0,0,0);
//        $zhongcaiyuan = Db::name('arbitrator')->where('dossier_id',1)->where('status',1)->value('name');
//        dump($zhongcaiyuan);
//        dump($res);

//        dump(PublicNumber::getCode());

//        dump(Db::query("ALTER TABLE `zc_access_token` ADD `openid` VARCHAR(100) NOT NULL , ADD INDEX (`openid`) "));
//        dump(Db::query("ALTER TABLE `zc_access_token` ADD `state` INT NOT NULL COMMENT '自定义' AFTER `scope`, ADD INDEX (`state`) ;"));
//        dump(Db::query("ALTER TABLE `zc_access_token` ADD `scope` VARCHAR(50) NOT NULL COMMENT '应用授权作用域，snsapi_base （不弹出授权页面，直接跳转，只能获取用户openid），snsapi_userinfo （弹出授权页面，可通过openid拿到昵称、性别、所在地。并且， 即使在未关注的情况下，只要用户授权，也能获取其信息 ）' AFTER `openid`;"));
        dump(Db::name('access_token')->select());
//        echo  phpinfo();
    }

    public function sms()
    {
        $res = Notice::sendSms('','');

        dump($res);
    }

    public function saveToken()
    {
//        dump(Db::name('access_token')->where("id=34")->data(['expires_time'=>1522202241])->update());
        $json = ' {
     "button":[
     {
          "type":"click",
          "name":"今日歌曲",
          "key":"V1001_TODAY_MUSIC"
      },
      {
           "name":"菜单",
           "sub_button":[
           {
               "type":"view",
               "name":"搜索",
               "url":"http://www.soso.com/"
            },
            {
                 "type":"miniprogram",
                 "name":"wxa",
                 "url":"http://mp.weixin.qq.com",
                 "appid":"wx286b93c14bbf93aa",
                 "pagepath":"pages/lunar/index"
             },
            {
               "type":"click",
               "name":"赞一下我们",
               "key":"V1001_GOOD"
            }]
       }]
 }';

        $josn2 = '{
    "button": [
        {
            "name": "扫码",
            "sub_button": [
                {
                    "type": "scancode_waitmsg",
                    "name": "扫码带提示",
                    "key": "rselfmenu_0_0",
                    "sub_button": [ ]
                },
                {
                    "type": "scancode_push",
                    "name": "扫码推事件",
                    "key": "rselfmenu_0_1",
                    "sub_button": [ ]
                }
            ]
        },
        {
            "name": "发图",
            "sub_button": [
                {
                    "type": "pic_sysphoto",
                    "name": "系统拍照发图",
                    "key": "rselfmenu_1_0",
                   "sub_button": [ ]
                 },
                {
                    "type": "pic_photo_or_album",
                    "name": "拍照或者相册发图",
                    "key": "rselfmenu_1_1",
                    "sub_button": [ ]
                },
                {
                    "type": "pic_weixin",
                    "name": "微信相册发图",
                    "key": "rselfmenu_1_2",
                    "sub_button": [ ]
                }
            ]
        },
        {
            "name": "发送位置",
            "type": "location_select",
            "key": "rselfmenu_2_0"
        },
        {
           "type": "media_id",
           "name": "图片",
           "media_id": "MEDIA_ID1"
        },
        {
           "type": "view_limited",
           "name": "图文消息",
           "media_id": "MEDIA_ID2"
        }
    ]
}';
//        dump(\GuzzleHttp\json_decode($json,true));
//        dump(\GuzzleHttp\json_decode($josn2,true));
        dump(Dossier::getSimpleDossier(1)['zc_jg_id']);
        $zcw_phones = array_column((array)Db::name('jigou_admin')->where('th_id',Dossier::getSimpleDossier(1)['zc_jg_id'])->where('status',1)->select(),'phone','idid');

        dump($zcw_phones);
    }

    public function testtest()
    {
        $res = Dnotice::whenDmpFinish(12,1,0,0,0,true);
        dump($res);
    }

    public function testXml()
    {
        $xml = $obj2="<xml><ToUserName><![CDATA[gh_055eb98ef774]]></ToUserName>
<FromUserName><![CDATA[oMW-u0SiYggyLWs-Gs_F25kJ7nCk]]></FromUserName>
<CreateTime>1528298529</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[subscribe]]></Event>
<EventKey><![CDATA[]]></EventKey>
</xml>";

        $link = 'http://zcw.wszx.cc/admin/Wxcallback/index';

        $res = \wslibs\wszc\publicnumber\Config::curl_post($link,$xml);

        dump($res);
    }
    public function dumpIdcard()
    {
        $state = '88449';
        $type =2;
        $time = time();
        if($type==2){
            $map = "expires_time>'$time' and type='$type'  and state='$state'";
        }else{
            $map = "expires_time>'$time' and type='$type'";
        }
        $res =  Db::name('access_token')->where($map)->order('id desc')->value('access_token');
        dump($res);
    }

    public function dili(){
        $xml = '<xml><ToUserName><![CDATA[gh_055eb98ef774]]></ToUserName>
<FromUserName><![CDATA[oMW-u0SiYggyLWs-Gs_F25kJ7nCk]]></FromUserName>
<CreateTime>1528272381</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[LOCATION]]></Event>
<Latitude>38.015469</Latitude>
<Longitude>114.436661</Longitude>
<Precision>790.000000</Precision>
</xml>';
        $xml2 = '<xml><ToUserName><![CDATA[gh_055eb98ef774]]></ToUserName>
<FromUserName><![CDATA[oMW-u0SiYggyLWs-Gs_F25kJ7nCk]]></FromUserName>
<CreateTime>1528272278</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[subscribe]]></Event>
<EventKey><![CDATA[]]></EventKey>
</xml>';
        $xml3 = '<xml><ToUserName><![CDATA[gh_055eb98ef774]]></ToUserName>
<FromUserName><![CDATA[oMW-u0SiYggyLWs-Gs_F25kJ7nCk]]></FromUserName>
<CreateTime>1528272997</CreateTime>
<MsgType><![CDATA[event]]></MsgType>
<Event><![CDATA[TEMPLATESENDJOBFINISH]]></Event>
<MsgID>313410580507885569</MsgID>
<Status><![CDATA[success]]></Status>
</xml>';

        $xml4 = '<xml><ToUserName><![CDATA[gh_055eb98ef774]]></ToUserName>
<FromUserName><![CDATA[oMW-u0SiYggyLWs-Gs_F25kJ7nCk]]></FromUserName>
<CreateTime>1528331048</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[帅哥]]></Content>
<MsgId>6564131869071914632</MsgId>
</xml>';

        $xml5 = '<xml><signature><![CDATA[a84a71f9d9f3453a3a414823b60938ef6a211873]]></signature><timestamp>1528355955</timestamp><nonce>452388337</nonce><openid><![CDATA[oMW-u0SiYggyLWs-Gs_F25kJ7nCk]]></openid><encrypt_type><![CDATA[aes]]></encrypt_type><msg_signature><![CDATA[1345907e491c3b0bc2a2ef33d733eb2005069f06]]></msg_signature></xml>';
        $res = \wslibs\wszc\publicnumber\Config::xmlToArray($xml);
        $res1 = \wslibs\wszc\publicnumber\Config::xmlToArray($xml2);
        $res3 = \wslibs\wszc\publicnumber\Config::xmlToArray($xml3);
        $res4 = \wslibs\wszc\publicnumber\Config::xmlToArray($xml4);
        $res5 = \wslibs\wszc\publicnumber\Config::xmlToArray($xml5);
//        dump( ReplyMsg::replyMsg($xml4));
        dump($res);
        dump($res1);
        dump($res3);
        dump($res4);
        dump($res5);
    }


    public function addOtherInfo()
    {
//        $xml = '<xml><ToUserName><![CDATA[gh_055eb98ef774]]></ToUserName>
//<FromUserName><![CDATA[oMW-u0SiYggyLWs-Gs_F25kJ7nCk]]></FromUserName>
//<CreateTime>1528272381</CreateTime>
//<MsgType><![CDATA[event]]></MsgType>
//<Event><![CDATA[LOCATION]]></Event>
//<Latitude>38.015469</Latitude>
//<Longitude>114.436661</Longitude>
//<Precision>790.000000</Precision>
//</xml>';
//        dump( ReplyMsg::replyMsg($xml));
        dump(Db::name('access_other_info')->select());
    }


    public function encode()
    {
        $xml = '<xml><ToUserName><![CDATA[oMW-u0SiYggyLWs-Gs_F25kJ7nCk]]></ToUserName><FromUserName><![CDATA[gh_055eb98ef774]]></FromUserName><CreateTime>1528332351</CreateTime><MsgType><![CDATA[text]]></MsgType><Content><![CDATA[哎呀,人家都不好意思了]]></Content></xml>';

        $data = array(
            "ToUserName" => "oMW-u0SiYggyLWs-Gs_F25kJ7nCk",
            "FromUserName" => "gh_055eb98ef774",
            "CreateTime" => 1528332351,
            "MsgType" => "text",
            "Content" => "哎呀,人家都不好意思了",
        );

        $res  = new MsgCrypt();

        $res->encryptMsg($data,time(),(new Prpcrypt())->getRandomStr(),$msg);

        $result = $res->encryptMsg($data,time(),987654321,$msg);

        dump($result);
        dump($msg);
    }

    public function decode()
    {
        $list = $this->dealdATA();
        $timestamp  = $list['timestamp'];
        $nonce = $list['nonce'];
        $msg_signature  = $list['msg_signature'];
        $openid  = $list['openid'];
        $encrypt_type = $list['encrypt_type'];
        $signature = $list['signature'];

        $encode = '<xml>
    <ToUserName><![CDATA[gh_055eb98ef774]]></ToUserName>
    <Encrypt><![CDATA[Et6nIAG/PPRp6+3iHD90IHqyTxMKW1non0t8rU52DVr2ZJR7LLl6uNfSFQSJ/n2SFWD/O8YHuuFIchSnD5Hphziunh54t5ZH67z0+CYnFL5yIHMIwnsraiAvSRKz/m+91FYqoVQI/ZYAOnLLxvpV+8MFXno9nztfsfnwLmHW8y7jQieaSIsT9nWes6b4oG1h/OgKbaVmnac4N8BqmTVQD1kzj/W0T2W1FPUIC5EzPQZ8N+pwZExs5mCLzqb5K+j79GBDowC1u+SVr/7TJSggfvujyvwxs7jM64B+bruAVfnfRtEGE7izIqrFOp6sdBpknK/rdzGClW50OUTCXolTQJNVMr7J2neu9CcjKTJS/q/jxnMe9PeaE8EUQpncfV8nKII+B4N6LZXywKgt++Hn7FU/lepyWteW+Uq4wEyNx3A=]]></Encrypt>
</xml>';
        $res = (new WXBizMsgCrypt())->decryptMsg($msg_signature,$timestamp,$nonce,$encode,$msg);

        if($res<0){
            echo  $res;
            exit;
        }

        dump($msg);

        $msgReply = ReplyMsg::replyMsg($msg);

        if($msgReply=='success'){
            echo $msgReply;
            exit;
        }

        (new WXBizMsgCrypt())->encryptMsg(\wslibs\wszc\publicnumber\Config::arrayToXml($msgReply),$timestamp,$nonce,$msg);

        dump($msg);
    }

    public function dealdATA()
    {
        $xml5 = '<xml><signature><![CDATA[7bc70ffd0e3f566aaa150fbd846f6d73dfd37463]]></signature><timestamp>1528456474</timestamp><nonce>643915047</nonce><openid><![CDATA[oMW-u0SiYggyLWs-Gs_F25kJ7nCk]]></openid><encrypt_type><![CDATA[aes]]></encrypt_type><msg_signature><![CDATA[33450596cd9012c7be1406d460b094383a57d3b1]]></msg_signature></xml>';

        return \wslibs\wszc\publicnumber\Config::xmlToArray($xml5);
    }

    public function testToken()
    {

        dump($name =  Db::name("dossier_users")->where("dossier_id", 43)->select() );
        dump(Db::name('dz')->where('dossier_id',40)->select());
        dump($dz_info['addtime'] = max(array_column((array)Db::name('dz')->where('dossier_id',40)->select(),'addtime')));
    }

    public function inform()
    {

        dump(Db::name("inform")->alias('i')->order('i.id desc')->select());

    }


    public function getBtn()
    {
        $res = (new NewsModelWithDo())->getBtn();

        DUMP($res);
    }


    public function new_send()
    {
        $dossier_info = Db::name('dossier')->where("id=84")->find();
//        $res1 = Dnotice::sendGid_19($dossier_info,4,19,0);
//        $res2 = Dnotice::sendGid_18($dossier_info,14,18,0);
//        $res3 = Dnotice::sendGid_17($dossier_info,17,17,0);
//        $res7 = Dnotice::sendGid_7($dossier_info,166,20,0);
//        $res4 = Dnotice::sendGid_6($dossier_info,166,20,0);
//        $res5 = Dnotice::sendGid_5($dossier_info,166,20,0);
//        $res6 = Dnotice::sendGid_4($dossier_info,4,4,0);
//        $res8 = Dnotice::sendGid_3($dossier_info,166,20,0);
//        dump($res1);
//        dump($res2);
//        dump($res3);
//        dump($res7);
//        dump($res4);
//        dump($res5);
//        dump($res6);
//        dump($res8);

//        $res1 = Dnotice::sendGid_27($dossier_info,166,27,0);
//        dump(Db::name('msg_record')->order('id desc')->select());

//        $users = \wslibs\wszc\Dossier::getDangShiRen(166, 0);

//        dump($users);


//        $res1 = Dnotice::sendGid_31($dossier_info,166,31,0);
//        $res2 = Dnotice::sendGid_33($dossier_info,166,33,0);
//        $res3 = Dnotice::sendGid_34($dossier_info,166,34,0);
//        $res4 = Dnotice::sendGid_40($dossier_info,166,40,0);

//        $res1 = Dnotice::sendGid_36($dossier_info,166,31,0);
//        $res2 = Dnotice::sendGid_37($dossier_info,166,37,0);
//
//        $res4 = Dnotice::sendGid_39($dossier_info,166,40,0);
//        $res5 = Dnotice::sendGid_41($dossier_info,166,41,0);
//        $res6 = Dnotice::sendGid_20($dossier_info,19,20,0);
//        $res7 = Dnotice::sendGid_22($dossier_info,166,22,0);
//        $res8 = Dnotice::sendGid_23($dossier_info,166,23,0);
//        $res9 = Dnotice::sendGid_25($dossier_info,166,25,0);
//        $res10 = Dnotice::sendGid_27($dossier_info,84,27,0);
//        $res10 = Dnotice::sendGid_10($dossier_info,166,10,0);

//        dump($res1);
//        dump($res2);
//
//        dump($res4);
//        dump($res5);
//        dump($res6);
//        dump($res7);
//        dump($res8);
//        dump($res9);
//        dump($res10);

        (new NewsModel(84))->zhongcaiCaiJueShuTongZhi(2,'oMW-u0SiYggyLWs-Gs_F25kJ7nCk','');

        echo 'ok';
    }

    public function new_dmail()
    {
       dump( Notice::sendSms('13933863958','你长得真帅'));
       dump( Notice::sendSms('15201634344','你长得真帅'));
       dump( Notice::sendSms('15832192235','你长得真帅'));
    }


    public function dash()
    {
        $line = new DashboardLine();
        list($paylist,$createlist) = $line->getSevenCount();
//        $_3 = $line->getSevenCount();

            dump($paylist);
            dump($createlist);
//            dump($_3);

    }
    //->field("FROM_UNIXTIME(d.addtime, '%Y-%m-%d') as add_time,if(t.time20>0,COUNT(*),0) AS count_sq, if(t.time30 >0,count(*),0) as count_sl")->group("add_time")
    public function var_dump(){

        (new Dmail())->sendShouLiWenjianToShenQingRen(80);
//        (new Dmail())->sendShouLiWenjianToBeiShenQingRen(6);

//        $count = Db::name('dossier')->alias('d')->join('dossier_time t','d.id=t.id','left')->where("d.zc_jg_id=10")->select();
//        dump($count);
    }



    public function test_defence()
    {
        $remain_defence = Db::name("dossier_defence")->whereIn("dossier_id", [1,2,3,4,5,6,7,8,9])->group("dossier_id")->field("dossier_id,group_concat(addtime) as defence_addtime,count(*) as d_num")->select();
        $dangshirens1 = Db::name("dossier_question")->whereIn("dossier_id", [1,2,3,4,5,6,7,8,9])->group("dossier_id")->field("dossier_id,group_concat(addtime) as question_addtime,count(*) as q_num")->select();


        $remain_defence = array_map(function($value){

            $value['defence_addtime'] = '剩余:'.implode(',',array_map(function($val){

                $val = ceil(($val+86400*5-time())/86400).'天';
                dump($val);
                return $val;
            },explode(',',$value['defence_addtime'])));

            return $value;
        },$remain_defence);

        dump($remain_defence);
    }



    public function kfcount()
    {
//        dump(Zhz::kfcount());

        $xml = '<xml><ToUserName><![CDATA[gh_055eb98ef774]]></ToUserName>
<FromUserName><![CDATA[oMW-u0SiYggyLWs-Gs_F25kJ7nCk]]></FromUserName>
<CreateTime>1529545550</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[哈喽]]></Content>
<MsgId>6569348115443058783</MsgId>
</xml>';
        echo $xml;
        $res = ReplyMsg::replyMsg($xml);

        dump($res);
        echo \wslibs\wszc\publicnumber\Config::arrayToXml($res);
        dump( \wslibs\wszc\publicnumber\Config::arrayToXml($res));

    }


    public function addUserInfo()
    {


        $data = [];
        $data['idid'] = 1;
        $data['openid'] = 'sdhsldkaldjaljaldhan';
        $data['nickname'] = '浪小志';
        $data['sex'] = 1;
        $data['province'] = '河北';
        $data['city'] = '石家庄';
        $data['country'] = '中国';
        $data['headimgurl'] = 'www.baidu.com';
        $data['privilege'] = 'www.baidu.com';
        $data['unionid'] = 'www.baidu.com';
        $res = Db::name('access_user_info')->insert($data);
        dump($res);
    }





    public function dumpAccessToken()
    {
//
//        $es = Db::name('access_token')->whereIn("id",[142,143])->delete();
//        dump($es);
//
//
        $list = Db::name('access_token')->order('id desc')->select();

        foreach($list as $key=>$value){
            $list[$key]['add_time'] = date('Y-m-d H:i:s',$value['add_time']);
            $list[$key]['expires_time'] = date('Y-m-d H:i:s',$value['expires_time']);
        }
        dump($list);

        dump(Db::name('access_user_info')->select());
    }

    public function getKf()
    {
        $list = Kfinfo::getKfOnlineList();
        $list1 = Kfinfo::getKfList();

        dump($list);
        dump($list1);
    }

    public function kf()
    {
        $xml = '<xml><ToUserName><![CDATA[gh_055eb98ef774]]></ToUserName>
<FromUserName><![CDATA[oMW-u0SiYggyLWs-Gs_F25kJ7nCk]]></FromUserName>
<CreateTime>1529722207</CreateTime>
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[我现在]]></Content>
<MsgId>6570106851480697863</MsgId>
</xml>';

        $res = ReplyMsg::replyMsg($xml);
        if($res=='success'){
            echo $res;
            exit;
        }
        dump($res);
        echo \wslibs\wszc\publicnumber\Config::arrayToXml($res);
        dump(\wslibs\wszc\publicnumber\Config::arrayToXml($res));
    }



    public function testerror()
    {
//        $this->error('测试错误');
        echo $background = Config::get('fastadmin.login_background');
        exit;
        $this->success('测试成功');
    }


    public function teste()
    {
        $users = \wslibs\wszc\Dossier::getDangShiRen(129, 0);
        foreach($users as $key=>$value){
            if($value['role']==3 || $value['role']==4){
                unset($users[$key]);
            }
        }
        $dangshiren = array_column($users, 'name');

        dump($users);
        dump($dangshiren);

    }

    public function dangqian()
    {
//        WsExce::dsend(260, 27, 0);
//        (new NewsModel(260))->zhongcaiCaiJueShuTongZhi(2,'oMW-u0SiYggyLWs-Gs_F25kJ7nCk','');
        echo '杀戮都市但是看到';
        echo '<br>';
//        (new Dmail())->sendShouLiWenjianToBeiShenQingRen(278);
        (new Dmail())->sendShouLiWenjianToShenQingRen(260);
        echo '杀戮都市但是看到';
    }

    public function dmail_test()
    {
        $did = $_GET['did'];
        echo date('Y-m-dH:i:s',time());

        echo '<br>';
//        (new Dmail())->sendShouLiWenjianToShenQingRen($did);
//        (new Dmail())->sendShouLiWenjianToBeiShenQingRen($did);
//        (new Dmail())->sendGuanXiaQuanAllPeoples($did,44,80);
//        (new Dmail())->sendQuestionZhengJu($did,18,384);

//        (new Dmail())->sendQuestionZhengJu($did,18,384);
//        (new Dmail())->sendQuestionZhengJu1($did,18,384);


//        (new Dmail())->sendZhengjuZhuanfa($did,26,299);
//        (new Dmail())->sendDaBianZhengJu($did,19,203);
//        (new Dmail())->sendCaiJueAllPeoples($did,27,260);
//        (new Dmail())->sendShengmingAllPersons($did,22,370);
//        (new Dmail())->sendZuTingAllPersons($did,4,'',1);
        (new Dmail())->sendCheHuiApplyAllPeoples(225,36,13);

        echo date('Y-m-dH:i:s',time());
    }

    public function dmail_test1111()
    {
        $did = $_GET['did'];
        echo date('Y-m-dH:i:s',time());

        echo '<br>';
        (new Dmail())->sendShouLiWenjianToShenQingRen($did);
        (new Dmail())->sendShouLiWenjianToBeiShenQingRen($did);
        (new Dmail())->sendGuanXiaQuanAllPeoples($did,44,80);
        (new Dmail())->sendQuestionZhengJu($did,18,384);
        (new Dmail())->sendZhengjuZhuanfa($did,26,299);
        (new Dmail())->sendDaBianZhengJu($did,19,203);
        (new Dmail())->sendCaiJueAllPeoples($did,27,260);
        (new Dmail())->sendShengmingAllPersons($did,22,370);
        (new Dmail())->sendZuTingAllPersons($did,4,91,1);

        echo date('Y-m-dH:i:s',time());
    }



    public function zcymingce()
    {
//        $res6 = Dnotice::whenDmpFinish(228,36,18,0,0);
//
//        dump($res6);
//
//        exit;

        $res = Db::name("gxq_yy")->whereIn('status',[2,7,8])->column("d_id");

        dump($res);
//        return $this->fetch('wsdoc/doc/zcymingce');
    }


    public function gxqyy()
    {
        $res = Db::name("gxq_yy")->whereIn('status',[2,7,8])->column("d_id");

        dump($res);
    }


}
