<?php

/**
 * Created by PhpStorm.
 * User: apple
 * Date: 2018/6/19
 * Time: 下午5:44
 */
use app\common\controller\Frontend;
class Aboutme extends Frontend
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}